version: '{branch}-{build}'
build: off

platform:
  - x86
  - x64

environment:
  global:
    PYTHONUNBUFFERED: True
    PYTHONWARNINGS: 'ignore:::wheel.pep425tags:'
    CONDA_BLD: C:\miniconda35

  matrix:
    - PYTHON_VERSION: 2.7
    - PYTHON_VERSION: 3.3
    - PYTHON_VERSION: 3.4
    - PYTHON_VERSION: 3.5
    - PYTHON_VERSION: 3.6

init:
  # Prepare Environment
  - mkdir C:\testdir

  # Set environment variables depending based on build cfg
  - set CONDA_PY=%PYTHON_VERSION:.=%
  - set CONDA_BLD_ARCH=%PLATFORM:x=%
  - set PYTHON=C:\PYTHON%PYTHON_VERSION:.=%
  - if %PLATFORM%==x86 (set CONDA_BLD_ARCH=32)
  - if %PLATFORM%==x64 (set PYTHON=%PYTHON%-x64)
  - if %PLATFORM%==x64 (set CONDA_BLD=%CONDA_BLD%-x64)

  # Prepend newly installed Python to the PATH of this build
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

install:
  - pip install --upgrade -r requirements.txt

  # Install OpenCover. Can't put on `packages.config`, not Mono compatible
  - .\tools\nuget\nuget.exe install OpenCover -OutputDirectory packages

build_script:
  # Create clean `sdist`. Only used for releases
  - python setup.py --quiet sdist
  # Build `wheel` with coverage of `setup.py`
  - coverage run setup.py bdist_wheel

test_script:
  - pip install --no-index --find-links=.\dist\ pythonnet
  - ps: Copy-Item (Resolve-Path .\build\*\Python.Test.dll) C:\testdir

  - ps: .\ci\appveyor_run_tests.ps1
  - ps: .\ci\appveyor_build_recipe.ps1

on_finish:
  # Upload coverage
  - codecov

artifacts:
  - path: dist\*

notifications:
  - provider: Slack
    incoming_webhook:
      secure: 2S/t6rGHdbwoxehnvn5KgfsHrBFEtwnPD7M5olGErmz70oWFVpqoWd/EvDwh7rKZGdOTjDmpwcukc2xi5VRaGHbBAqFYS3tAdgAMrcaTNWs=
